version: 2
updates:

  # Docker app image.

    - package-ecosystem: docker
      directory: "./.docker/nginx/Dockerfile"
      registries: "*"
      schedule:
        interval: daily
      open-pull-requests-limit: 10
      commit-message:
        prefix: "[Updated]"
      ignore:
        - dependency-name: "*"
          update-types:
            - "version-update:semver-major"
            - "version-update:semver-minor"

    - package-ecosystem: docker
      directory: "./.docker/php/8.0/Dockerfile"
      registries: "*"
      schedule:
        interval: daily
      open-pull-requests-limit: 10
      commit-message:
        prefix: "[Updated]"
      ignore:
        - dependency-name: "*"
          update-types:
            - "version-update:semver-major"
            - "version-update:semver-minor"

    - package-ecosystem: docker
      directory: "./.docker/php/8.1/Dockerfile"
      registries: "*"
      schedule:
        interval: daily
      open-pull-requests-limit: 10
      commit-message:
        prefix: "[Updated]"
      ignore:
        - dependency-name: "*"
          update-types:
            - "version-update:semver-major"
            - "version-update:semver-minor"

    - package-ecosystem: docker
      directory: "./.docker/mysql/Dockerfile"
      registries: "*"
      schedule:
        interval: daily
      open-pull-requests-limit: 10
      commit-message:
        prefix: "[Updated]"
      ignore:
        - dependency-name: "*"
          update-types:
            - "version-update:semver-major"
            - "version-update:semver-minor"

    - package-ecosystem: docker
      directory: "./.docker/redis/Dockerfile"
      registries: "*"
      schedule:
        interval: daily
      open-pull-requests-limit: 10
      commit-message:
        prefix: "[Updated]"
      ignore:
        - dependency-name: "*"
          update-types:
            - "version-update:semver-major"
            - "version-update:semver-minor"
